Repository Les-Informatichiens/InformatiChats, pull requests merged in 2023-08, with the labels that each got.

#15 Window imgui abstraction layer
  CMakeLists.txt
  src/ChatApp.cpp
  src/ChatApp.h
  src/View/Backend/GLFWWindowManager.cpp
  src/View/Backend/GLFWWindowManager.h
  src/View/Backend/IWindow.h
  src/View/GUI/IGUIManager.h
  src/View/GUI/ImGuiManager.hpp
  src/View/Panels/UserInfoPanel.cpp
  src/main.cpp
Labels: enhancement

#20 Changed websocket to be secured
  src/Model/ChatClient.cpp
  src/Model/Model.cpp
Labels: bug

#21 User cannot enter empty name anymore
  CMakeLists.txt
  src/View/Panels/ChatPanel.cpp
  src/View/Panels/LoginPanel.cpp
  src/View/Panels/LoginPanel.h
  src/util/string_util.cpp
  src/util/string_util.h
Labels: invalid

#26 remodelling --literally
  CMakeLists.txt
  src/ChatApp.cpp
  src/ChatApp.h
  src/Controller/ChannelController.cpp
  src/Controller/ChannelController.h
  src/Controller/ChatController.cpp
  src/Controller/ChatController.h
  src/Controller/IChannelController.h
  src/Controller/LoginController.cpp
  src/Controller/LoginController.h
  src/Controller/ViewModels/ChannelViewModel.h
  src/Controller/ViewModels/ChatViewModel.h
  src/Controller/ViewModels/LoginViewModel.h
  src/Model/ApplicationLogic/UserLogic.cpp
  src/Model/ApplicationLogic/UserLogic.h
  src/Model/BinarySerializer.h
  src/Model/DataAccess/IChatAPI.h
  src/Model/DataAccess/LibDataChannelChatAPI.cpp
  src/Model/DataAccess/LibDataChannelChatAPI.h
  src/Model/IUser.h
  src/Model/Model.cpp
  src/Model/Model.h
  src/Model/Models/ChatMessage.h
  src/Model/Models/PeerData.h
  src/Model/Models/User.h
  src/Model/User.cpp
  src/Model/User.h
  src/Model/modelspec.txt
  src/View/Panels/ChannelPanel.cpp
  src/View/Panels/ChannelPanel.h
  src/View/Panels/ChatPanel.cpp
  src/View/Panels/ChatPanel.h
  src/View/Panels/LoginPanel.cpp
  src/View/Panels/LoginPanel.h
  src/View/Panels/UserInfoPanel.cpp
  src/View/Panels/UserInfoPanel.h
  src/View/Views/ChannelView.cpp
  src/View/Views/LoginView.cpp
  src/main.cpp
  src/util/string_util.cpp
Labels: enhancement
